services:
  hrk.realtime:
    build:
      args:
        BUILD_CONFIGURATION: Debug
    labels:
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages \"/app/bin/Debug/net9.0/HRK.REALTIME.dll\""

