<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GAME.Domain\GAME.Domain.csproj" />
    <ProjectReference Include="..\GAME.Application\GAME.Application.csproj" />
    <ProjectReference Include="..\..\..\CoreEngine\Core.Common\Core.Common.csproj" />
    <ProjectReference Include="..\..\..\CoreEngine\Core.RabbitMQ\Core.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\..\CoreEngine\Core.Messaging.Contracts\Core.Messaging.Contracts.csproj" />
    <ProjectReference Include="..\..\..\CoreEngine\Core.TransactionalMessaging\Core.TransactionalMessaging.csproj" />
  </ItemGroup>

</Project>
