<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Activity.Domain/Activity.Domain.csproj" />
    <ProjectReference Include="../../../CoreEngine/Core.Messaging.Contracts/Core.Messaging.Contracts.csproj" />
  </ItemGroup>
</Project>
